CodePasteMvc/Controllers/SnippetController.cs
using System;
using System.Web;
using System.Web.Mvc;
using CodePasteBusiness;
using Westwind.Web.Mvc;
using Westwind.Utilities;
using System.Text;
using System.Collections.Generic;
using System.Web.Routing;
using System.Linq;
using System.Collections;
using System.IO;
using Manoli.Utils.CSharpFormat;
using Westwind.Utilities.InternetTools;

namespace CodePasteMvc.Controllers
{    
    public class SnippetController : ApiControllerBase
    {

        
        public SnippetController()
        {

        }

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            this.ViewData["AllowEdit"] = false;            
        }


        public ActionResult Show(string id)
        {
            ShowSnippetViewModel model = new ShowSnippetViewModel(this);
            model.AppUserState = AppUserState;
            
            // Since this is our default handler anything invalid will
            // run through here. No path - go to new
            if (string.IsNullOrEmpty(id) || id == "0")
                return this.New();

            using (busCodeSnippet busSnippet = new busCodeSnippet())
            {
                var snippet = busSnippet.Load(id);
                if (snippet == null)
                {
                    return this.DisplayErrorPage("Invalid Snippet Id specified",
                        "You specified a snippet id or link that is invalid and cannot be displayed. " +
                        "Please using the <a href='./recent' class='hoverbutton'>Recent Snippets</a> or " +
                        "<a href='mysnippets' class='hoverbutton'>My Snippets</a> buttons to look up valid snippets.", null);
                }

                bool allowWordWrap = false;
                bool showLineNumbers = busSnippet.Entity.ShowLineNumbers;

                string ua = Request.UserAgent.ToLower();
                if (ua.Contains("iphone") ||
                    ua.Contains("blackberry") ||
                    ua.Contains("mobile"))
                {
                    allowWordWrap = true;
                    showLineNumbers = false;
                }
                

                // Update the code so it's formatted
                model.FormattedCode = busSnippet.Entity.FormattedCode;
                if (!AppUserState.IsEmpty())
                    model.IsFavoritedByUser = busSnippet.IsFavorite(busSnippet.Entity.Id, AppUserState.UserId);


                if (!string.IsNullOrEmpty(AppUserState.UserId) &&
                    AppUserState.UserId == busSnippet.Entity.UserId || AppUserState.IsAdmin)
                    model.AllowEdit = true;

                // explicitly load up comments
                busSnippet.Entity.Comments = busSnippet.GetComments();

                // For API result we have to make sure email and password are not included            
                if (!string.IsNullOrEmpty(Format) && snippet.User != null)
                {
                    busSnippet.StripSensitiveUserInformation();  
                }
                if (snippet.User != null)
                {
                    if (!string.IsNullOrEmpty(snippet.User.Theme))
                        model.Theme = snippet.User.Theme;
                }

                ActionResult actionResult = this.ApiResult(busSnippet.Entity);
                if (actionResult != null)
                    return actionResult;

                model.Snippet = busSnippet.Entity;

                // Fix up for Ace Editor
                model.Snippet.Language = busSnippet.FixUpLanguage(model.Snippet.Language).ToLower();

                // Log views for all but poster
                if (model.Snippet.User == null ||
                    model.Snippet.User.Id != AppUserState.UserId)
                    busSnippet.LogSnippetView(busSnippet.Entity.Id, Request.UserHostAddress, Request.UserAgent);

                return View("Show",model);
            }
        }

        /// <summary>
        /// Displays a snippet as raw HTML
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ShowHtml(string id)
        {
            using (busCodeSnippet busSnippet = new busCodeSnippet())
            {
                var snippet = busSnippet.Load(id);

                if (snippet == null)
                    return new HttpNotFoundResult();

                if (snippet.Language.ToLower() != "html")
                    return new HttpNotFoundResult("Invalid snippet type");

                return this.Content(snippet.Code);
            }
        }


        public ActionResult CodeOnly(string id)
        {
            ShowSnippetViewModel model = new ShowSnippetViewModel(this);
            model.AppUserState = this.AppUserState;

            // Since this is our default handler anything invalid will
            // run through here. No path - go to new
            if (string.IsNullOrEmpty(id) || id == "0")
                return this.New();

            using (busCodeSnippet busSnippet = new busCodeSnippet())
            {
                if (busSnippet.Load(id) == null)
                {
                    ErrorDisplay.ShowError("Invalid snippet id specified.");
                    model.Snippet = new CodeSnippet();
                    return View(model);
                }

                model.Snippet = busSnippet.Entity;

                // Update the code so it's formatted
                model.FormattedCode = busSnippet.Entity.FormattedCode;

                if (!string.IsNullOrEmpty(AppUserState.UserId) && AppUserState.UserId == busSnippet.Entity.UserId || AppUserState.IsAdmin)
                    model.AllowEdit = true;

                ActionResult result = View(model);
                string output = result.ToString();

                return result;
            }
        }

        public ActionResult ShowUrl()
        {
            string url = Request.QueryString["url"];
            string lang = Request.QueryString["language"];
            if (string.IsNullOrEmpty(lang))
                lang = Request.QueryString["lang"] ?? string.Empty;

            if (lang.ToLower() == "csharp")
                lang = "C#";                

            ShowSnippetViewModel model = new ShowSnippetViewModel(this);
            model.AppUserState = this.AppUserState;

            ViewData["originalUrl"] = url;
            ViewData["fileName"] = Path.GetFileName(url);
            ViewData["language"] = lang;

            if (string.IsNullOrEmpty(url))
            {
                ViewData["languageList"] = this.GetLanguageList(lang);
                return View(model);
            }

            HttpClient client = new HttpClient();
            client.Timeout = 4000;
            
            string result = client.DownloadString(url);

            if (result == null)            
                return 
                    this.DisplayErrorPage("Unable to retrieve Code Url", client.ErrorMessage, null);

            if (result.Length > App.Configuration.MaxCodeLength)
                return this.DisplayErrorPage("Snippet is too large", "Your code snippet to display is too long. Snippets can be no larger than " + App.Configuration.MaxCodeLength.ToString("n0") + " bytes.",null);

            busCodeSnippet snippetBusiness = new busCodeSnippet();

            if (string.IsNullOrEmpty(lang))
            {
                string extension = Path.GetExtension(url).ToLower();
                
                if (extension.StartsWith("."))
                    lang = extension.Substring(1);
            }

            model.FormattedCode = snippetBusiness.GetFormattedCode(result, lang, false, false);
            
            snippetBusiness.Dispose();

            return this.View(model);
        }
        

        public ActionResult New(string message = null)
        {
            ViewData["UserState"] = AppUserState;

            var snippet = new CodeSnippet();
            snippet.Author = this.AppUserState.Name;

            string codeUrl = Request.QueryString["url"];            

            if (!string.IsNullOrEmpty(codeUrl))
            {                
                HttpClient client = new HttpClient();
                client.Timeout = 4000;
                snippet.Code = client.DownloadString(codeUrl);

                snippet.Title = Path.GetFileName(codeUrl); 
                string extension = Path.GetExtension(codeUrl);

                snippet.Language = CodeFormatFactory.GetStringLanguageFromExtension(extension);    
                Response.Write(snippet.Language);
            }

            if (!string.IsNullOrEmpty(message))            
                this.ErrorDisplay.ShowMessage(message);
            
            return this.View("New",snippet);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateInput(false)]
        public ActionResult New(FormCollection formValues)
        {
            ViewData["UserState"] = AppUserState;
            ViewData["languageList"] = this.GetLanguageList();

            busCodeSnippet busSnippet = new busCodeSnippet();
            CodeSnippet snippet = busSnippet.NewEntity();
            if (snippet == null)
            {
                ErrorDisplay.ShowError("Couldn't load snippet");
                return View(new CodeSnippet());
            }

            UpdateModel(snippet);                      

            if (!ValidateForSpam(snippet))
            {
                this.ErrorDisplay.ShowError("Invalid data posted back.");
                return View(snippet);
            }
            
            if (!busSnippet.Validate())
            {
                foreach (ValidationError error in busSnippet.ValidationErrors)
                {
                    this.ErrorDisplay.AddMessage(error.Message, error.ControlID);
                }
                this.ErrorDisplay.ShowError("Please correct the following:");

CodePasteMvc/Views/Snippet/CodeOnly.cshtml
@model CodePasteMvc.Controllers.ShowSnippetViewModel
<!DOCTYPE html>
<html>
<head>
    <title>CodePaste.NET - @Model.Snippet.Title</title>    
    <meta id="metaKeyWords" name="Keywords" content="@Model.Snippet.Tags" />
    <meta id="metaDescription" name="Description" content="CodePage.NET - paste and link .NET code for referencing from Social Network sites. Store and organize your code snippets."  />
    <link href="~/Css/csharp.css" rel="stylesheet" type="text/css" />    
    <style type="text/css">
     </style>
</head>
<body >
    <div class="codedisplay">@Html.Raw(Model.FormattedCode)</div>
</body>  
</html>  

CodePasteMvc/Views/Snippet/LanguageDropdown-Partial.cshtml
<select id="Language" name="Language" size="1">
    <option value="text">-- No Code Formatting --</option>
    <optgroup label="Common">
        <option value="html">HTML</option>
        <option value="javascript">JavaScript</option>
        <option value="typescript">TypeScript</option>
        <option value="jsx">React JSX</option>
        <option value="json">JSON</option>
        <option value="xml">XML</option>
        <option value="css">CSS</option>
        <option value="less">Less</option>
        <option value="sass">Sass</option>
        <option value="csharp">C#</option>
        <option value="c_cpp">C/C++</option>
        <option value="foxpro">FoxPro</option>
        <option value="swift">Swift</option>
        <option value="sql">SQL</option>
        <option value="sqlserver">SQL Server</option>
        <option value="python">Python</option>
        <option value="ruby">Ruby</option>
        <option value="php">PHP</option>        
        <option value="java">Java</option>
    </optgroup>
    <optgroup label="Everything Else">
        <option value="actionscript">ActionScript</option>
        <option value="apache_conf">Apache Conf</option>
        <option value="assembly_x86">Assembly x86</option>
        <option value="batchfile">BatchFile</option>
        <option value="clojure">Clojure</option>
        <option value="cobol">Cobol</option>
        <option value="coffee">CoffeeScript</option>
        <option value="coldfusion">ColdFusion</option>
        <option value="css">CSS</option>
        <option value="dart">Dart</option>
        <option value="dockerfile">Diff</option>
        <option value="diff">Docker</option>
        <option value="elixir">Elxir</option>
        <option value="elm">Elm</option>
        <option value="erlang">Erlang</option>
        <option value="groovy">Groovy</option>
        <option value="gitignore">GitIgnore</option>
        <option value="haml">HAML</option>
        <option value="handlebars">Handlebars</option>
        <option value="haskell">Haskell</option>
        <option value="html_ruby">HTML (Ruby)</option>
        <option value="ini">INI</option>
        <option value="jade">Jade</option>
        <option value="java">Java</option>
        <option value="javascript">JavaScript</option>
        <option value="json">JSON</option>
        <option value="jsp">JSP</option>
        <option value="jsx">JSX</option>
        <option value="latex">LaTeX</option>
        <option value="less">LESS</option>
        <option value="lisp">Lisp</option>
        <option value="lucene">Lucene</option>
        <option value="makefile">Makefile</option>
        <option value="markdown">Markdown</option>
        <option value="mysql">MySQL</option>
        <option value="pascal">Pascal</option>
        <option value="perl">Perl</option>
        <option value="powershell">Powershell</option>
        <option value="prolog">Prolog</option>
        <option value="python">Python</option>
        <option value="razor">Razor</option>
        <option value="ruby">Ruby</option>
        <option value="sass">SASS</option>
        <option value="scala">Scala</option>
        <option value="sqlserver">Sql Server</option>
        <option value="svg">SVG</option>
        <option value="swift">Swift</option>
        <option value="typescript">Typescript</option>
        <option value="vbnet">VB.NET</option>
        <option value="vbscript">VBScript</option>
        <option value="xml">XML</option>
        <option value="xquery">XQuery</option>
        <option value="yaml">YAML</option>
    </optgroup>
</select>

CodePasteMvc/Views/Snippet/List.cshtml
@using System.Web.UI.WebControls
@using CodePasteBusiness
@using CodePasteMvc
@using CodePasteMvc.Controllers
@using Westwind.Utilities
@using Westwind.Web
@using Westwind.Web.Mvc
@{
    Layout = "~/views/shared/_layout.cshtml";
}
@section headers {

    <title>CodePaste.Net - Snippet Listing</title>
    <meta id="metaKeyWords" name="Keywords" content="CodePaste,Paste,Code,DotNet,.Net,C#,ASP.NET,AJAX,JQuery,Rick Strahl,HTML,CSS,JavScript,ADO.Net,West Wind Technologies,WebLog,Blog" />
    <meta id="metaDescription" name="Description" content="CodePage.NET - paste and link .NET code for referencing from Social Network sites. Store, link and organize your code snippets." />
    <script src="~/Scripts/List.js" type="text/javascript"></script>

    <style type="text/css">
    </style>
}
@{
    // Create serverVars instance for JavaScript vars visible in .js file
    var serverVars = new JsonVariables( "serverVars");
    serverVars.Add("baseUrl", Request.ApplicationPath);
    serverVars.Add("callbackHandler", Url.Content("~/CodePasteHandler.ashx"));
    Response.Write("<script>" + serverVars.ToHtmlString(true) + "</script>");

    // simplify strongly typed var access in View
    busCodeSnippet busSnippet = ViewData["busSnippet"] as busCodeSnippet;
    IEnumerable<CodeSnippetListItem> snippetList = ViewData["SnippetList"] as IEnumerable<CodeSnippetListItem>;
    string title = ViewData["PageTitle"] as string ?? string.Empty;
    CodePasteMvc.Controllers.SnippetController controller = ViewContext.Controller as CodePasteMvc.Controllers.SnippetController;
    AppUserState UserState = ViewData["UserState"] as AppUserState;
}

@Html.Raw(((ErrorDisplay)this.ViewData["ErrorDisplay"]).Show(450, true))

<div class="rightalign" style="font-size: 0.825em">
    Format:
    <select id="ApiFormats" style="font-size: 8pt">
        <option value="Html">Web Page</option>
        <option value="Xml" title="?format=xml">Xml</option>
        <option value="Json" title="?format=json">Json</option>
        <option value="Rss" title="?format=rss">Rss Feed</option>
        <option value="Atom" title="?format=atom">Atom Feed</option>
    </select>
</div>
<div class="listpageheader">@title</div>

@{
    bool OddEven = true;
    foreach (CodeSnippetListItem snip in snippetList)
    {

        <div class="@( !string.IsNullOrEmpty(snip.UserId) && snip.UserId == UserState.UserId ? "snippetofauthor" : "snippet")" id="snippet_@snip.Id">
            <div class="snippetlang">
                @if(snip.Language != "text" && snip.Language != "NoFormat")
                {
                    <a href="~/list/language/@snip.Language">@snip.Language</a>
                }
            </div>
            <div class="snippettitle">
                <a href='@Url.Action("Show", new {id = snip.Id})'>
                    @(string.IsNullOrEmpty(snip.Title) ?
                    "No Title" :
                    snip.Title)
                </a>

            </div>
            <div class="snippetcode">
                <pre>@busSnippet.GetCodeLines(snip.Code, 10)</pre>
            </div>

            <div class="toolbarcontainer" style="margin-top: 5px;">
                <div class="snippetauthor">@Html.Raw(!string.IsNullOrEmpty(snip.Author) ? " by " + snip.GetAuthorLink() + "&nbsp;&nbsp;" : string.Empty)   @TimeUtils.FriendlyDateString(snip.Entered, true)</div>
                <div><small>Tags: @Html.Raw(Url.GetTagLinkList(snip.Tags))</small></div>
            </div>

            <div class="rightalign">
                @if (snip.Views > 1)
            {
                    <div class="viewcount">
                        @snip.Views Views
                    </div>
            }

                <div class="snippetcommentcount">
                    @(snip.CommentCount < 1 ? "no" : snip.CommentCount.ToString()) comments
                </div>
            </div>

            @if (UserState.IsAdmin)
        {
            <div style="font-size: smaller; margin: 5px 0">
                <a href="javascript:{}" class="removelink">Remove Snippet</a> |
                <a href="javascript:{}" class="removeUserLink" data-userid="@snip.UserId">Remove User</a>

            </div>
        }
        else
        {
                <span>&nbsp;</span>
        }
        </div>
    }
}

CodePasteMvc/Views/Snippet/New.cshtml
@model CodePasteBusiness.CodeSnippet
@using System.Web.UI.WebControls
@using CodePasteMvc
@using Westwind.Web
@{
    Layout = "~/views/shared/_layout.cshtml";
    AppUserState userState = ViewData["UserState"] as AppUserState;           
}
@section headerstop {
    <title>New Code Snippet - Codepaste.net</title>
    <meta id="metaKeyWords" name="Keywords" content="CodePaste,Paste,Code,DotNet,.Net,C#,ASP.NET,AJAX,JQuery,HTML,CSS,JavScript,ADO.Net"  />
 	<meta id="metaDescription" name="Description" content="CodePage.NET - paste and link .NET code for referencing from Social Network sites. Store, link and organize your code snippets."  />
}
@section headers {
    <script src="~/scripts/new.js"></script>
    <style>
        .containercontent input[type=text],
        .containercontent textarea {
            width: 100%;            
        }
         .ace_editor, .ace_editor * {
             font-family: "Liberation Mono", Consolas, "Courier New", monospace !important;
             font-size: 10pt !important;
             font-weight: normal;
             letter-spacing: 0;            
         }
        .ace_content {
            padding-top: 5px !important;
        }
        .ace_heading {
            font-weight: bold !important;   
        }
        .ace_strong {
            font-weight: bold !important;
        }
        .ace_emphasis {
            font-style: italic !important;
        }  
    /*.ace_scrollbar {
                display: none !important;
            }*/
    </style>

}
    
    @Html.Raw(((Westwind.Web.Mvc.ErrorDisplay) this.ViewData["ErrorDisplay"]).Show(400,true) )

    <form id="snippetform" action="new" method="post">
            <div class="containercontent">
                <div style="float: right; margin-bottom: 8px;">
                    <b>Syntax:</b>
                    @Html.Partial("LanguageDropdown-Partial")

                    @*<b><input type="checkbox" id="Private" name="Private" /><label for="Private">Private Snippet</label></b>*@
                </div>

                <div class="labelheader">Title:</div>
                <input type="text" name="Title" id="Title"  value="@Model.Title"  placeholder="Enter a descriptive title for your snippet"/>
                
                <div style="border: 1px solid silver; width: 100%;margin-top: 5px;">
                    <div id="CodeDisplay" class="codedisplay" style="min-height: 250px;">@Model.Code</div>
                    <input type="hidden" id="Code" name="Code" />
                </div>
                                

                <div class="fieldmessage" style="float: right">(left margins are automatically stripped from code)</div>
                @Html.CheckBox("ShowLineNumbers", Model.ShowLineNumbers) <label for="ShowLineNumbers" class="labelheader" style="display: inline" title="Determines if line numbers are displayed by default (can be overridden)">Show Line Numbers</label>

                <div class="labelheader" style="margin-top: 15px;">Tags: <small>(separate with commas)</small></div>
                <input type="text" name="Tags" id="Tags" style="width: 100%;" value="@this.Model.Tags" placeholder="Comma separated list of tags that describe this snippet." />

                <div class="labelheader">Comment: <small>(optional)</small></div>
                <textarea id="Comment" name="Comment" style="width: 100%; height: 50px;" placeholder="Any additional descriptive notes you might have about this code snippet">@this.Model.Comment</textarea>

                <div class="labelheader">Your Name: <small>(optional)</small></div>
                <input type="text" name="Author" id="Author" style="width: 100%;" value="@this.Model.Author" />

                <input type="submit" id="btnPaste" name="btnPaste" value="Paste your Code" class="pagesubmitbutton" style="width: 150px;" />
                <div class="fieldmessage">(JavaScript required for SPAM prevention)</div>
            </div>        
    </form>       
    
    <div id="divSignInNag" class="dialog dialog-content" style="width: 350px; display: none; position: absolute; z-index: 10000">
        <h3>You're not signed in</h3>
        
        <p>
            Signing in allows you to track and edit your code snippets after you've created them.
            You can quickly register and sign in - it only takes a minute and provides
            many usage enhancements.
        </p>
        <p>
            Anonymous snippets are allowed, but they are removed after 10 days.
        </p>        
        @Html.ActionLink("Sign in or Register","LogOn","Account",null, new { @class="hoverbutton" } )        
    </div>
        
    @if (Request.HttpMethod == "GET" && string.IsNullOrEmpty(userState.UserId))
    {
        <script type="text/javascript">
            $(document).ready(function() {
                showLayover();
            });
        </script>
    }




@section scripts{
    @{
        // server side variables persisted into JavaScript
        JsonVariables scriptVars = new JsonVariables("serverVars");
        scriptVars.Add("showLineNumbers", false);
        scriptVars.Add("allowEdit", true);
        scriptVars.Add("baseUrl", Url.Content("~/"));
        scriptVars.Add("theme", userState.Theme);
        scriptVars.Add("callbackHandler", Url.Content("~/CodePasteHandler.ashx"));
    }
    <script>
        @scriptVars.ToHtmlString(true)
    </script>
    <script src="~/Scripts/Ace/ace.js"></script>    
    <script src="~/Scripts/aceEditorConfig.js"></script>
    <script>
        window.aceEditor = configureAceEditor(serverVars);
        aceEditor.focus();

        $("#Language").change(function() {
            var lang = $(this).val();
            aceEditor.getSession().setMode("ace/mode/" + lang);
        });
    </script>

    @*
    <!-- typo.js integration -->
    <script src="~/Scripts/typo.js"></script>
    <script>
        // You also need to load in typo.js and jquery.js

        // You should configure these classes.
        var editor = "CodeDisplay"; // This should be the id of your editor element.
        var lang = "en_US";
        var dicPath = "./scripts/en-US.dic.txt";
        var affPath = "./scripts/en-US.aff.txt";

        // Make red underline for gutter and words.
        $("<style type='text/css'>.ace_marker-layer .misspelled { position: absolute; z-index: -2; border-bottom: 1px solid red; margin-bottom: -1px; }</style>").appendTo("head");
        $("<style type='text/css'>.misspelled { border-bottom: 1px solid red; margin-bottom: -1px; }</style>").appendTo("head");

        // Load the dictionary.
        // We have to load the dictionary files sequentially to ensure
        var dictionary = null;
        $.get(dicPath, function(data) {
            dicData = data;
        }).done(function() {
            $.get(affPath, function(data) {
                affData = data;
            }).done(function() {
                console.log("Dictionary loaded");
                dictionary = new Typo(lang, affData, dicData);
                enable_spellcheck();
                spell_check();
            });
        });

        // Check the spelling of a line, and return [start, end]-pairs for misspelled words.
        function misspelled(line) {
            var words = line.split(' ');
            var i = 0;
            var bads = [];
            for (word in words) {
                var x = words[word] + "";
                var checkWord = x.replace(/[^a-zA-Z']/g, '');
                if (!dictionary.check(checkWord)) {
                    bads[bads.length] = [i, i + words[word].length];
                }
                i += words[word].length + 1;
            }
            return bads;
        }

        var contents_modified = true;

        var currently_spellchecking = false;

        var markers_present = [];
        window.typoLastAccess = new Date().getSeconds();

        // Spell check the Ace editor contents.
        function spell_check() {
            // Wait for the dictionary to be loaded.
            if (dictionary == null) {
                return;
            }
            if (currently_spellchecking) {
                return;
            }

            if (!contents_modified) {
                return;
            }
            currently_spellchecking = true;
            var session = ace.edit(editor).getSession();

            // Clear the markers.
            for (var i in markers_present) {
                session.removeMarker(markers_present[i]);
            }
            markers_present = [];

            try {
                var Range = ace.require('ace/range').Range
                var lines = session.getDocument().getAllLines();
                for (var i in lines) {
                    // Clear the gutter.
                    session.removeGutterDecoration(i, "misspelled");
                    // Check spelling of this line.
                    var misspellings = misspelled(lines[i]);

                    // Add markers and gutter markings.
                    if (misspellings.length > 0) {
                        session.addGutterDecoration(i, "misspelled");
                    }
                    for (var j in misspellings) {
                        var range = new Range(i, misspellings[j][0], i, misspellings[j][1]);
                        markers_present[markers_present.length] = session.addMarker(range, "misspelled", "typo", true);
                    }
                }
            } finally {
                currently_spellchecking = false;
                contents_modified = false;
            }
        }

        function enable_spellcheck() {
            ace.edit(editor).getSession().on('change', function(e) {
                contents_modified = true;
            });
            setInterval(spell_check, 1000);
        }
    </script>
    *@
}

CodePasteMvc/Views/Snippet/ShowUrl.cshtml
@using Westwind.Utilities
@using Westwind.Web.Mvc
@model CodePasteMvc.Controllers.ShowSnippetViewModel
@{
    Layout = "~/views/shared/_layout.cshtml";
}
@section headers{
    <title>CodePaste.NET</title>        
    <style type="text/css">
        .commentedit {width: 400px;height: 70px; }
        .tagedit {width: 400px;height: 15px; }
        #divViews {float: left;
            margin: 5px;
            padding-left: 20px;
            font-size: .825em;
            font-weight: bold;
            background-image: url(css/images/users.gif);
            background-repeat: no-repeat;
        }
    </style>
}


                
    @Html.Raw(( (ErrorDisplay) this.ViewData["ErrorDisplay"]).Show(400,true))
    
    
    @if (string.IsNullOrEmpty(ViewData["originalUrl"] as string))
    {
        <form action="" method="get">
            <h2>Display Syntax  Colored Code from a URL</h2>
        
            <p>
                Below you can enter a url to a page that returns raw code from a source repository or
                other source and have it displayed with syntax coloring. You can also specify the url
                and language via query string. The url referenced must respond within 2 seconds.

            </p>
            
            <div style="margin: 20px 0;">
                <div class="labelheader">Web Location of raw unformatted code:</div>
                <input type="text" id="url" name="url" value="@ViewData["originalUrl"]"  style="width: 99.5%"/>
                
                <div class="labelheader">Code syntax:</div>
                @Html.DropDownList("Language", ViewData["languageList"] as List<SelectListItem>)      
                       
                <div>
                    <input type="submit" id="btnSubmit" value="Show highlighted code" 
                           class="pagesubmitbutton"  style="width: 150px; margin-top: 20px;"/> 
                </div>                                
            </div>
            
            <hr />
            <div class="smalltext">                
                Alternately you can also specify the <b>Url</b> and <b>Language</b> as query string parameters. 
                Check the URL after you've used the form above for syntax.                
            </div>
            
        </form>
    }
    else
    {

        <h2>@ViewData["fileName"]</h2>

        <div class="toolbarcontainer">
            <a href="@ViewData["originalUrl"]" class="hoverbutton" 
               title="View the original source code link on the Web"
               target="_blank">            
                @Html.Raw(HtmlUtils.ImgRef("~/images/OriginalUrl.png"))
                Source Url
            </a>        
        
            <a href="@(Url.Action("new", "Snippet", new {url = ViewData["originalurl"] as string}))"
               title="Creates a permanent snippet from this code" class="hoverbutton">
                @Html.Raw(HtmlUtils.ImgRef("~/css/images/newsnippet.gif"))  Create Snippet</a>
        </div>

        <div class="codedisplay">            
            <div id="CodeDisplay">@Html.Raw(Model.FormattedCode)</div>
        </div>
    }       